# Generated by Django 4.2 on 2023-04-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ownerId', models.IntegerField()),
                ('itemId', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutMethods',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('methodType', models.CharField(max_length=100)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userCategory', models.CharField(max_length=100)),
                ('ruleParameter', models.CharField(max_length=100)),
                ('ruleValue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderedBy', models.IntegerField()),
                ('orderedOn', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('billingProfile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.billingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCharges',
            fields=[
                ('chargeId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField()),
                ('billingProfile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.billingprofile')),
                ('eligibility', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.eligibility')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentRef', models.CharField(
                    max_length=100, primary_key=True, serialize=False)),
                ('transactionId', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('checkoutMethod', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.checkoutmethods')),
                ('order', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('discountID', models.AutoField(primary_key=True, serialize=False)),
                ('ownerId', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('validTill', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('billingProfile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.billingprofile')),
                ('eligibility', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='billingApp.eligibility')),
            ],
        ),
        migrations.AddField(
            model_name='checkoutmethods',
            name='eligibility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='billingApp.eligibility'),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='billingRules',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='billingApp.billingrules'),
        ),
    ]
