# Generated by Django 4.2 on 2023-04-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'verbose_name': 'Billing Profile',
                     'verbose_name_plural': 'Billing Profiles'},
        ),
    ]
